version: '3' 
services:
  sqlectron-docker:
    image: openkbs/eclipse-photon-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eclipse-photon-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      - DISPLAY=${DISPLAY:-":0.0"}
    env_file:
      - ./.env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./.eclipse-workspace:/home/developer/eclipse-workspace
      - ./.eclipse:/home/developer/.eclipse
    expose:
      - "61616"
      - "8161"
    ports:
      - "61616:61616/tcp"
      - "127.0.0.1:8161:8161"

